### ISSUE TITLE
Implement option to perform basic faction setup instead of the faction draft

### ISSUE THREAD

**Issue by DonatoVT** [EwenDC/root-automated-setup#18]
If you have only the base game selected it is impossible to select a player count of 4. Tried on multiple browsers, both iOS and MacOS platforms.

**Comment by MHostile** [comment]
Same issue here on Android, Chrome, French. Number of players can only be 2 or 3 with only the base game selected.

**Comment by EwenDC** [comment]
Hi @DonatoVT, Unfortunately this is not a bug but a consequence of the Advanced Setup Rules. For advanced setup to take place, you must have one more faction than the final player count. If you did not, then the last player to choose a faction (first in turn order) would be forced to pick whatever the remaining faction was.

This isn't really a situation Leder catered for in the setup, since it ships with the Marauder expansion, which would give you access to enough factions for a 5 player advanced setup game. I'm open to a change to allow you to setup with 4 players with just base factions, but I'd want to make it clear that it breaks the adset rules to do so.

**Comment by DonatoVT** [comment]
@EwenDC - understood. I was thinking more of it as a general setup guide than an AdSet guide, which is a failure of reading comprehension on my part as it clearly states "advanced setup" in the opening paragraph. Thanks!

**Comment by therealppa** [comment]
It would be great to have a way to skip the draft and instead just show all the factions available to pick from. This would also enable playing with 4 with only the base game. Would this be a feature you'd be interested in building? Should it be a separate Github issue?

**Comment by EwenDC** [comment]
Honestly, the faction draft is a significant portion of the reason why this app exists in the first place. Turning it off feels like it removes the primary benefit of using it. Without the faction draft and just the base game, the only thing the app is actually doing is choosing a first player, randomising the map, and formatting the setup rules in a fancy way. Not that the faction draft setup is particularly useful with just the base game, but this app (just like the adset rules themselves) was really intended to solve the problem of cleanly integrating 3+ expansions worth of content into the setup.

If the nicely formatted setup rules is considered a good enough reason on it's own to use the app, then really what is needed is a way to switch to basic setup rules. I will say right out of the gate that is going to be a massive feature to implement, considering this whole app was written from the ground up with adset in mind, and I am unlikely to prioritise it over other features. If that sounds like something you would like to see happen, feel free to create a separate issue for it. Otherwise we can keep tracking the discussion for this issue here.

In regards to this, I was thinking of adding a setup settings panel for enabling various house-rules to modify setup. A basic solution would be a checkbox allowing the draft to occur with the same number of players and factions. We could also have a checkbox for replacing the draft with a random faction assignment to each player, if that is something people would find valuable.

**Comment by EwenDC** [comment]
So I was re-reading the Adset rules, and it explicitly states that during the faction setup stage you can chose between the draft or the standard faction setup. So I'll add support for that since it's officially part of Adset.

There will be a checkbox on the choose factions step, to select if you want to use the draft or the standard setup. If the player count matches the faction count we just hide this checkbox and always use the standard setup.

**Comment by EwenDC** [comment]
Added in latest release!
