### ISSUE TITLE
Add Select All/Deselect All buttons to ComponentToggle

### ISSUE THREAD

**Issue by EwenDC** [EwenDC/root-automated-setup#21]
Can be implemented either as:

- Two buttons that are always showing (Select All and Deselect All)
- One button that changes contextually (Show Deselect All if all are selected, or Select All otherwise)

**Comment by steevefontaine** [comment]
Just translated the "Enable All"/"Disable All" buttons to French.

**Comment by EwenDC** [comment]
Cheers! Feel free to make a pull request and I can get the translations merged in.

**Comment by steevefontaine** [comment]
> Cheers! Feel free to make a pull request and I can get the translations merged in.

Hi @EwenDC. I am trying to push my modifications but I can't do it. I have a branch "fr-translation" on my local repository with the changes on the fr.ts file. In Visual Studio Code, I right-click that branch and select "Push Branch". It gets me an error message: "No anonymous write access".

So I am wondering: am I not doing the right thing? or is my VS Code not set properly? or is this just normal due to restricted rights on the distant repository?

I can't say that using git is one of my skills. :)

![Capture d’écran du 2023-11-05 19-54-20](https://github.com/EwenDC/root-automated-setup/assets/15193230/a5e49c77-616f-4c3f-97b4-37de357c2560)
![Capture d’écran du 2023-11-05 19-54-37](https://github.com/EwenDC/root-automated-setup/assets/15193230/857419cb-0f9f-4486-9772-622b5e6464fc)
![Capture d’écran du 2023-11-05 19-54-43](https://github.com/EwenDC/root-automated-setup/assets/15193230/1e95c237-ebba-4c67-bf9a-5994924f8086)

Any idea how to help me?

**Comment by EwenDC** [comment]
Hi @steevefontaine, you probably need to set up your computer to be authenticated with the repository. [Github has some documentation on how to do this](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). Sorry I can't help further than that, I usually use a dedicated Git client to commit (either Github Desktop or SourceTree).

**Comment by EwenDC** [comment]
If all else fails you can attach the updated translations here and I can get it merged in myself 🙂
